from __future__ import annotations

from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Dict, List

import streamlit as st

from core.loader import DataLoader
from core.pdf_extractor import PDFExtractor, PDFExtractionResult
from ui.pdf_preview_page import PDFPreviewPage


DOC_TYPES = ["Auto-detect", "PO", "GRN", "INV"]


def _ensure_session_defaults() -> None:
    st.session_state.setdefault("df_po", None)
    st.session_state.setdefault("df_grn", None)
    st.session_state.setdefault("df_inv", None)


def render() -> None:
    """
    Step 1: Upload spreadsheets and ingest via DataLoader.
    """
    _ensure_session_defaults()

    st.header("Step 1 — Upload Documents")
    st.markdown(
        "Upload your **Purchase Orders (PO)**, **Goods Receipt Notes (GRN)**, "
        "and **Invoices (INV)** as Excel, CSV, or PDF files."
    )

    uploaded_files = st.file_uploader(
        label="Upload PO, GRN, and Invoice files",
        type=["xlsx", "xls", "csv", "pdf"],
        accept_multiple_files=True,
        help=(
            "Accepted formats: Excel (.xlsx, .xls), CSV (.csv), PDF (.pdf)\n\n"
            "For PDF files: Tables are automatically extracted. "
            "Best results with text-based PDFs (not scanned images)."
        ),
    )

    if not uploaded_files:
        st.info("Upload at least one PO, GRN, or Invoice file to continue.")
        return

    # Sidebar PDF tips
    with st.sidebar:
        with st.expander("📄 PDF Upload Tips", expanded=False):
            st.markdown(
                """
        **For best PDF extraction results:**

        ✅ **Use text-based PDFs**
        (generated by software, not scanned)

        ✅ **Bordered tables work best**
        (Camelot lattice mode)

        ✅ **Single table per page** preferred

        ⚠️ **Scanned PDFs** will not extract well
        → Convert with Adobe Acrobat first

        ⚠️ **Image-based PDFs** are not supported

        💡 **Alternative:** Open PDF in Microsoft Word
        → Save as Excel → Upload the .xlsx file

        **Supported extraction engines:**
        - 🥇 Camelot (lattice) — bordered tables
        - 🥈 Camelot (stream) — borderless tables
        - 🥉 tabula-py — general fallback
        - 🔧 pdfplumber — last resort
        """
            )

    # PDF extraction feedback
    render_pdf_feedback(uploaded_files)

    st.subheader("Document Type Confirmation")
    st.caption(
        "The app will attempt to auto-detect document types, but you can override "
        "them below if necessary."
    )

    # Let user optionally specify explicit types; we will still auto-detect
    # via DataLoader and rely on its ambiguity flag for UI guidance.
    explicit_type_labels: Dict[str, str] = {}
    for f in uploaded_files:
        col1, col2 = st.columns([3, 1])
        with col1:
            st.text(f.name)
        with col2:
            choice = st.selectbox(
                "Type",
                DOC_TYPES,
                key=f"doctype_{f.name}",
            )
            if choice != "Auto-detect":
                explicit_type_labels[f.name] = choice

    if st.button("Load Documents"):
        loader = DataLoader()
        temp_paths: List[Path] = []
        explicit_types: Dict[Path, str] = {}

        for f in uploaded_files:
            suffix = Path(f.name).suffix
            with NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                tmp.write(f.getbuffer())
                tmp_path = Path(tmp.name)
                temp_paths.append(tmp_path)
                if f.name in explicit_type_labels:
                    explicit_types[tmp_path] = explicit_type_labels[f.name]

        loaded = loader.load_files(temp_paths, explicit_types=explicit_types or None)

        st.session_state["df_po"] = loaded.df_po
        st.session_state["df_grn"] = loaded.df_grn
        st.session_state["df_inv"] = loaded.df_inv

        if loaded.manual_type_assignment_required and not explicit_type_labels:
            st.warning(
                "Some files could not be confidently classified. "
                "Consider specifying document types explicitly from the dropdowns above."
            )
        else:
            st.success("Documents loaded successfully. You can proceed to parameter selection.")


def render_pdf_feedback(uploaded_files):
    """Show PDF extraction status for any uploaded PDF files."""

    pdf_files = [f for f in uploaded_files if f.name.lower().endswith(".pdf")]

    if not pdf_files:
        return

    st.markdown("---")
    st.subheader("📄 PDF Extraction Status")

    for pdf_file in pdf_files:
        with st.expander(f"📄 {pdf_file.name}", expanded=True):
            from tempfile import NamedTemporaryFile as _NamedTmp
            import os as _os

            with st.spinner(f"Extracting tables from {pdf_file.name}..."):
                try:
                    extractor = PDFExtractor()

                    with _NamedTmp(delete=False, suffix=".pdf") as tmp:
                        tmp.write(pdf_file.getvalue())
                        tmp_path = tmp.name

                    result: PDFExtractionResult = extractor.extract(tmp_path)
                    _os.unlink(tmp_path)

                    col1, col2, col3, col4 = st.columns(4)

                    with col1:
                        st.metric("Pages", result.total_pages)
                    with col2:
                        st.metric("Tables Found", result.tables_found)
                    with col3:
                        method_labels = {
                            "camelot_lattice": "Camelot ✦",
                            "camelot_stream": "Camelot ~",
                            "tabula": "Tabula",
                            "pdfplumber": "pdfplumber",
                        }
                        st.metric(
                            "Method",
                            method_labels.get(result.extraction_method_used, "Auto"),
                        )
                    with col4:
                        confidence_colors = {
                            "HIGH": "🟢",
                            "MEDIUM": "🟡",
                            "LOW": "🔴",
                        }
                        best_conf = (
                            result.best_table.confidence
                            if result.best_table
                            else "LOW"
                        )
                        st.metric(
                            "Confidence",
                            f"{confidence_colors.get(best_conf, '🔴')} {best_conf}",
                        )

                    if result.best_table and result.best_table.warnings:
                        for w in result.best_table.warnings:
                            st.warning(f"⚠️ {w}")

                    if result.best_table:
                        detected = result.best_table.suggested_doc_type
                        type_colors = {
                            "PO": "blue",
                            "GRN": "green",
                            "INV": "orange",
                            "UNKNOWN": "red",
                        }
                        color = type_colors.get(detected, "red")
                        st.markdown(
                            f"**Detected Document Type:** "
                            f":{color}[{detected}]"
                        )

                        if detected == "UNKNOWN":
                            st.selectbox(
                                "⚠️ Could not auto-detect type. Please select:",
                                options=["PO", "GRN", "INV"],
                                key=f"manual_type_{pdf_file.name}",
                            )

                    if result.page_thumbnails:
                        st.markdown("**Page Preview:**")
                        thumb_cols = st.columns(
                            min(len(result.page_thumbnails), 4)
                        )
                        for i, thumb_bytes in enumerate(
                            result.page_thumbnails[:4]
                        ):
                            with thumb_cols[i]:
                                st.image(
                                    thumb_bytes,
                                    caption=f"Page {i+1}",
                                    use_column_width=True,
                                )

                    if result.best_table is not None:
                        st.markdown(
                            "**Extracted Table Preview (first 5 rows):**"
                        )

                        accuracy_pct = result.best_table.accuracy_score * 100

                        if accuracy_pct >= 90:
                            bar_color = "green"
                        elif accuracy_pct >= 70:
                            bar_color = "orange"
                        else:
                            bar_color = "red"

                        st.markdown(
                            f"Extraction accuracy: "
                            f"**:{bar_color}[{accuracy_pct:.1f}%]**"
                        )
                        st.progress(accuracy_pct / 100)

                        st.dataframe(
                            result.best_table.dataframe.head(5),
                            use_container_width=True,
                        )

                        st.caption(
                            f"Table has {result.best_table.row_count} rows "
                            f"× {result.best_table.col_count} columns."
                        )

                        # For medium/low confidence, surface column mapping UI
                        if result.best_table.confidence in {"MEDIUM", "LOW"}:
                            render_pdf_column_mapper(
                                pdf_file.name, result.best_table.dataframe
                            )

                        # For LOW confidence, allow opening full inspector
                        if result.best_table.confidence == "LOW":
                            if st.button(
                                "🔍 Open Detailed PDF Table Inspector",
                                key=f"inspect_{pdf_file.name}",
                            ):
                                st.session_state[f"inspect_{pdf_file.name}"] = True

                        if st.session_state.get(f"inspect_{pdf_file.name}", False):
                            inspector = PDFPreviewPage()
                            inspector.render(pdf_file, result)
                    else:
                        st.error(
                            "❌ No tables could be extracted from this PDF. "
                            "Please check that the PDF contains actual table "
                            "data (not a scanned image). "
                            "Try converting to Excel first using "
                            "Adobe Acrobat or Microsoft Word."
                        )

                except Exception as e:
                    st.error(f"❌ Extraction failed: {str(e)}")
                    st.info(
                        "💡 Tips:\n"
                        "- Make sure Ghostscript is installed on your system\n"
                        "- Try converting the PDF to Excel first\n"
                        "- Scanned PDFs (image-based) are not supported "
                        "— use a text-based PDF"
                    )


def render_pdf_column_mapper(pdf_file_name: str, df: pd.DataFrame):
    """
    If extracted PDF columns don't perfectly match expected column names,
    show a mapping UI so the user can manually assign columns.
    Called when confidence is MEDIUM or LOW.
    """

    from rapidfuzz import fuzz

    EXPECTED_COLUMNS = [
        "po_number",
        "vendor_name",
        "item_description",
        "line_item",
        "quantity",
        "unit_price",
        "amount",
        "doc_date",
    ]

    st.markdown(f"### 🗂️ Column Mapping for `{pdf_file_name}`")
    st.info(
        "Map the extracted PDF columns to the required field names. "
        "Skip any columns that don't apply."
    )

    extracted_cols = ["(skip)"] + list(df.columns)
    mapping: Dict[str, str] = {}

    cols_grid = st.columns(2)
    for i, expected in enumerate(EXPECTED_COLUMNS):
        with cols_grid[i % 2]:
            best_match = "(skip)"
            best_score = 0
            for col in df.columns:
                score = fuzz.token_sort_ratio(
                    expected.replace("_", " "), str(col).lower()
                )
                if score > best_score and score > 60:
                    best_score = score
                    best_match = col

            selected = st.selectbox(
                label=f"**{expected}** maps to:",
                options=extracted_cols,
                index=extracted_cols.index(best_match)
                if best_match in extracted_cols
                else 0,
                key=f"col_map_{pdf_file_name}_{expected}",
            )
            if selected != "(skip)":
                mapping[selected] = expected

    if st.button("✅ Apply Column Mapping", key=f"apply_map_{pdf_file_name}"):
        df_mapped = df.rename(columns=mapping)
        st.session_state[f"pdf_mapped_{pdf_file_name}"] = df_mapped
        st.success(
            f"Column mapping applied! {len(mapping)} columns mapped successfully."
        )
        st.dataframe(df_mapped.head(3), use_container_width=True)

